# =============================================================================
# app/scraper_service.py — BookingScraper Pro v6.0.0 Build 85
# =============================================================================
# BUILD 85 — BUG-BUILD-001-FIX (ver app/__init__.py para changelog completo)
#   - Headers de versión sincronizados: __init__.py / config.py / scraper_service.py
#   - schema_v77_complete.sql: v_hotels_full corregida (BUG-VIEW-001/002/003)
# BUILD 82 — GAP-API-001-FIX + GAP-SCHEMA-003-FIX
#
#   GAP-API-001: hotels_all_services.service_category — nueva columna.
#     Root cause: _extract_all_services() devolvía List[str] sin contexto
#     de grupo. La API destino requiere servicios categorizados. El método
#     _upsert_hotel_all_services() esperaba strings y no persistía categorías.
#     Fix:
#       - extractor.py: _extract_all_services() → List[Dict[str,str]]
#         {service, service_category}. Strategy 1.5 (facility-group) extrae
#         el heading del grupo como categoría. Otras estrategias usan "".
#       - scraper_service.py: _upsert_hotel_all_services() actualizado para
#         aceptar List[Dict] y persistir service_category.
#       - models.py + schema_v77_complete.sql: service_category VARCHAR(128) NULL.
#
#   GAP-SCHEMA-003: hotels_nearby_places.category_code — nueva columna.
#     Root cause: category almacenaba texto ("airport") pero la API espera
#     INTEGER. Faltaba columna category_code y mapa de conversión.
#     Fix:
#       - extractor.py: _extract_nearby_places() añade 'category_code' a cada
#         dict usando _NEARBY_CATEGORY_CODE_MAP (1-6).
#       - scraper_service.py: _upsert_hotel_nearby_places() persiste category_code.
#       - models.py: category_code Mapped[Optional[int]] SmallInteger.
#       - schema_v77_complete.sql: category_code SMALLINT NULL + chk constraint.
#
# =============================================================================
# BUILD 81 — GAP-SCHEMA-001-FIX
#
#   Root cause: hotels_individual_reviews table exists in schema_v77_complete.sql
#   and the HotelIndividualReview ORM model exists in models.py (Build 77).
#   main.py also queries and returns individual_review_rows. However:
#     - extractor.py had NO _extract_individual_reviews() method
#     - extract_all() never returned the 'individual_reviews' key
#     - scraper_service.py had NO _upsert_hotel_individual_reviews() method
#     - _persist_hotel_data() never called any individual-reviews upsert
#   Same silent-discard pattern as BUG-PERSIST-001/002/003 in Builds 63/77/78.
#
#   Fix:
#     - extractor.py: _extract_individual_reviews() implemented; selectors
#       data-testid="review-card/author/title/positive-text/negative-text/
#       author-country" with aria-label score fallback.  extract_all() now
#       includes 'individual_reviews' key.
#     - scraper_service.py: _upsert_hotel_individual_reviews() added;
#       delete-before-insert strategy (same as other list-type tables).
#       Called at the end of _persist_hotel_data() before session.commit().
#     - BUILD_VERSION bumped to 81 in app/__init__.py and app/config.py.
#
# =============================================================================
# BUILD 80 — GAP-SCHEMA-002-FIX
#
#   Root cause: HotelRoomType ORM model had adults, children, images, info
#   columns (added in v76 patch GAP-SCHEMA-002-FIX) but hotels_room_types
#   SQL table only had: id/hotel_id/url_id/language/room_name/description/
#   facilities/created_at.  SQLAlchemy emits INSERT with ALL mapped columns
#   → UndefinedColumn for adults, children, images, info on every room upsert.
#   Also: extractor only returned {name, description, facilities} — missing the
#   API-required adults/children/images/info keys entirely.
#
#   Fix:
#     - schema_v77_complete.sql: added adults SMALLINT, children SMALLINT,
#       images JSONB DEFAULT []::jsonb, info TEXT NULL to hotels_room_types
#     - extractor.py: _extract_room_types() now returns adults (SVG count),
#       children (SVG count), images [], info None in every room dict
#     - scraper_service.py: _upsert_hotel_room_types() persists all 4 new fields
#
# BUILD 79 — BUG-SCHEMA-002-FIX
#
#   Root cause: hotels.accommodation_type column existed in the Hotel ORM model
#   (models.py, GAP-EXTRACT-001-FIX v76 patch) but was NEVER added to the SQL
#   schema file. PostgreSQL raised UndefinedColumn on EVERY SELECT generated by
#   SQLAlchemy, since it always projects all mapped columns. This blocked 100%
#   of scrapes across all 14 URLs x 6 languages.
#
#   Fix:
#     - schema_v77_complete.sql: added accommodation_type VARCHAR(64) NULL
#       to the hotels table (after rooms_quantity, before version_id)
#     - extractor.py: _extract_json_ld() now captures @type as accommodation_type
#       and extract_all() includes it in the returned dict via JSON-LD merge
#     - scraper_service.py: _upsert_hotel() now writes accommodation_type field
#
# BUILD 78 — BUG-PERSIST-003-FIX
#
#   Root cause: _upsert_hotel_extra_info() was defined in ScraperService but
#   NEVER called inside _persist_hotel_data(). The hotels_extra_info table was
#   always empty even though _extract_extra_info() in extractor.py correctly
#   extracted the "Good to know / Información importante" block.
#
#   Same silent-discard pattern as BUG-PERSIST-001 (Build 63) and
#   BUG-PERSIST-002 (Build 77), where defined methods are never wired into
#   the persistence pipeline.
#
#   Fix: added self._upsert_hotel_extra_info() call in _persist_hotel_data()
#   alongside the other table-level upserts.
#
# =============================================================================
# BUILD 68 — BUG-VPN-001 FIX
#
#   Root cause: VPN_ROTATION_INTERVAL=50 was checked only at batch start
#   (dispatch_batch) and inside _scrape_language() guarded by should_rotate()
#   — meaning the time-based rotation NEVER fired between languages when all
#   fetches succeeded.  Also, error-triggered rotation inside _scrape_language()
#   was guarded by should_rotate() — so a failure immediately after a batch-
#   start rotation (< 50 s elapsed) would NOT rotate the VPN.
#
#   Evidence (logs 2026-04-02):
#     01:04:13  VPN connected to Sweden — IP: 79.116.133.126
#     01:04:29  SSL handshake failed; net_error -100   ← unstable tunnel
#     01:05:10  en: SUCCESS (page already buffered)
#     01:05:10  inter-language delay 11.6 s before …/es
#               VPN_ROTATION_INTERVAL=50 s had elapsed since 01:04:13
#               → should_rotate() True, but never called between languages
#               → VPN dropped completely during delay
#     [LOG ENDS — es/de/it/fr/pt never scraped]
#
#   Fix A — _process_url(): time-based rotation per language.
#     Check should_rotate() before EVERY language, not just at batch start.
#     If interval elapsed → rotate(force=False) and reset browser.
#     vpn_rotated flag ensures browser reset happens once via existing
#     BUG-LANG-002-FIX block.
#
#   Fix B — _scrape_language(): error-triggered rotation on every failure.
#     Removed should_rotate() guard.  Any fetch failure immediately triggers
#     rotate(force=True) regardless of elapsed time.
#
# BUILD 68 (VPN-PROACTIVE — preserved from prior commit):
#   dispatch_batch(): proactive rotation at batch start.
#
# BUILD 63-fix — ImportError — model names corrected to match app/models.py
#
#   WRONG  (Build 63):  from app.models import Hotels, ScrapingLogs
#   CORRECT:            from app.models import Hotel, ScrapingLogs
#
#   Pattern confirmed from schema_v60_complete.sql (source of truth):
#     SQL table          → Python model class
#     hotels             → Hotel
#     hotels_legal       → HotelLegal      (MODEL-002: HotelLegal.has_legal_content)
#     hotels_description → HotelDescription
#     hotels_policies    → HotelPolicies
#
# All other Build 63 logic (Selenium-only engine, BUG-LANG-001/002 fixes)
# is preserved unchanged.
# =============================================================================

from __future__ import annotations

import logging
import random
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Optional

from sqlalchemy.orm import Session

from app.config import get_settings
from app.database import get_db

# ─── CORRECTED MODEL IMPORTS ──────────────────────────────────────────────────
# Build 63 had:  from app.models import URLQueue, URLLanguageStatus, Hotels, ScrapingLogs
# Correct names derived from schema_v60_complete.sql MODEL-002 annotation:
from app.models import URLQueue, URLLanguageStatus, Hotel, ScrapingLogs
# ─────────────────────────────────────────────────────────────────────────────

from app.scraper import SeleniumEngine, build_language_url
from app.extractor import BookingExtractor
from app.image_downloader import ImageDownloader

logger = logging.getLogger(__name__)


# =============================================================================
# HELPERS
# =============================================================================

def _build_language_list(cfg) -> list[str]:
    """
    Build ordered language list: English always first, remainder as configured.
    """
    raw: list[str] = [
        lang.strip().lower()
        for lang in getattr(cfg, "ENABLED_LANGUAGES", "en,es,de,it,fr,pt").split(",")
        if lang.strip()
    ]
    if "en" in raw:
        raw.remove("en")
    return ["en"] + raw


def _get_vpn_manager(cfg):
    """Return the appropriate VPN manager based on VPN_ENABLED config."""
    if not getattr(cfg, "VPN_ENABLED", False):
        from app.vpn_manager_windows import NullVPNManager
        return NullVPNManager()
    try:
        from app.vpn_manager_windows import NordVPNManager
        # BUG-VPN-INIT-001-FIX (Build 86): NordVPNManager(cfg) passed the Settings
        # object as the 'interactive: bool' parameter → truthy value → interactive mode
        # enabled in all production Celery workers. Fixed to NordVPNManager().
        return NordVPNManager()
    except Exception as exc:
        logger.warning(
            "Could not initialise NordVPNManager: %s — using NullVPNManager", exc
        )
        from app.vpn_manager_windows import NullVPNManager
        return NullVPNManager()


# =============================================================================
# ScraperService
# =============================================================================

class ScraperService:
    """
    High-level orchestration for multi-language hotel scraping.

    Build 63: SeleniumEngine is the sole scraping engine.
    Build 63-fix: Model class names corrected (Hotel, not Hotels).
    """

    def __init__(self) -> None:
        self._cfg = get_settings()
        self._selenium_engine = SeleniumEngine()
        self._vpn = _get_vpn_manager(self._cfg)
        # BUG-EXTRACTOR-001 (Build 63-fix):
        #   BookingExtractor (alias of HotelExtractor) is NOT a stateless singleton.
        #   HotelExtractor.__init__ requires 'html' as a positional argument and
        #   parses the page at construction time.  It must be instantiated per
        #   language request inside _scrape_language(), not here.
        self._image_downloader = ImageDownloader()

    # ── Public interface ──────────────────────────────────────────────────────

    def dispatch_batch(self) -> dict:
        """
        Query URL queue for pending URLs and process them in parallel.
        """
        cfg = self._cfg
        max_workers: int = getattr(cfg, "SCRAPER_MAX_WORKERS", 2)

        with get_db() as session:
            pending = (
                session.query(URLQueue)
                .filter(URLQueue.status == "pending")
                .order_by(URLQueue.priority.desc(), URLQueue.created_at.asc())
                .limit(max_workers)
                .all()
            )

        if not pending:
            return {"status": "idle", "pending": 0}

        # VPN-PROACTIVE (Build 68): rotate VPN at the start of every batch.
        # NordVPNManager is recreated fresh for each task (_last_rotation=0),
        # so should_rotate() returns True immediately on every batch.
        # Without this block VPN only rotates reactively on failure — when all
        # hotels succeed the IP never changes despite VPN_ROTATION_INTERVAL=50.
        if getattr(cfg, "VPN_ENABLED", False) and self._vpn.should_rotate():
            _interval = getattr(cfg, "VPN_ROTATION_INTERVAL", 50)
            logger.info(
                "VPN-PROACTIVE: rotating before batch (threshold=%ds) — "
                "ensuring fresh IP for each batch",
                _interval,
            )
            try:
                _rotated = self._vpn.rotate()
                if _rotated:
                    logger.info("VPN-PROACTIVE: rotation successful — new IP secured")
                else:
                    logger.warning(
                        "VPN-PROACTIVE: rotation returned False — "
                        "proceeding with current IP"
                    )
            except Exception as _vpn_exc:
                logger.error(
                    "VPN-PROACTIVE: rotation error: %s — continuing with current IP",
                    _vpn_exc,
                )

        count = len(pending)
        logger.info("Dispatching %d URL(s) to %d worker(s)", count, max_workers)

        # BUG-COMMIT-STATUS-001-FIX (Build 87): Build 86 removed the explicit
        # session.commit() trusting get_db() to handle it.  That is correct
        # when the objects being modified were loaded in the *same* session.
        # Here however they were loaded in a *previous* get_db() block whose
        # session was already closed (and committed) before this block runs.
        # SQLAlchemy marks those objects as detached on session.close(); the
        # new session never tracks them, so the commit() in its __exit__ has
        # nothing to flush — url_queue rows stay 'pending' forever.
        #
        # Fix: extract the PKs from the (now detached but attribute-readable,
        # because expire_on_commit=False) objects and perform a single bulk
        # UPDATE inside a fresh session that owns the rows from the start.
        url_ids = [u.id for u in pending]
        with get_db() as session:
            session.query(URLQueue).filter(
                URLQueue.id.in_(url_ids)
            ).update(
                {"status": "processing", "updated_at": _now()},
                synchronize_session=False,
            )

        with ThreadPoolExecutor(max_workers=max_workers) as pool:
            futures = {
                pool.submit(self._process_url_safe, url_obj): url_obj
                for url_obj in pending
            }
            for future in as_completed(futures):
                url_obj = futures[future]
                try:
                    future.result()
                except Exception as exc:
                    logger.error(
                        "Unhandled error processing URL %s: %s",
                        url_obj.id, exc, exc_info=True,
                    )

        # BUG-BROWSER-001 (Build 63-fix): Brave stays open after batch
        # completes because SeleniumEngine uses a singleton driver that
        # persists until the Worker is stopped.  Calling reset_browser()
        # here quits the driver (driver.quit()) and sets self._driver=None
        # so the next batch starts with a clean profile.  This closes Brave
        # after every batch rather than leaving it open indefinitely on the
        # last scraped page.
        try:
            self._selenium_engine.reset_browser()
            logger.info("Selenium: Brave closed after batch completion.")
        except Exception as _exc:
            logger.warning("Selenium: reset_browser after batch raised: %s", _exc)

        return {"status": "done", "processed": count}

    def _process_url_safe(self, url_obj: URLQueue) -> None:
        """Wrapper around _process_url() that catches all exceptions."""
        try:
            self._process_url(url_obj)
        except Exception as exc:
            logger.error(
                "Fatal error in _process_url for %s: %s",
                url_obj.id, exc, exc_info=True,
            )
            self._mark_url_error(url_obj, str(exc))

    # ── Per-URL orchestration ─────────────────────────────────────────────────

    def _process_url(self, url_obj: URLQueue) -> None:
        """
        Iterate over all configured languages for a single URL.

        Build 61: Inter-language delay + forced VPN on consecutive failures.
        Build 62: ip_known_blocked flag + reset_browser() after VPN rotation.
        Build 63: Selenium-only (CloudScraper removed).
        """
        cfg = self._cfg
        url_id: str = str(url_obj.id)
        languages: list[str] = _build_language_list(cfg)

        consecutive_failures: int = 0
        max_consec: int = getattr(cfg, "MAX_CONSECUTIVE_LANG_FAILURES", 1)
        ip_known_blocked: bool = False

        completed: list[str] = []
        failed: list[str] = []

        for i, lang in enumerate(languages):

            # ── BUG-LANG-001-FIX-A: Inter-language delay ──────────────────────
            if i > 0:
                base_delay: float = getattr(cfg, "LANG_SCRAPE_DELAY", 10.0)
                jitter: float = random.uniform(
                    0.0, getattr(cfg, "LANG_SCRAPE_JITTER", 5.0)
                )
                total_delay: float = base_delay + jitter
                logger.info(
                    "BUG-LANG-001-FIX: inter-language delay %.1fs "
                    "(base=%.1f jitter=%.1f) before %s/%s",
                    total_delay, base_delay, jitter, url_id, lang,
                )
                time.sleep(total_delay)

            # ── BUG-VPN-001-FIX (Build 68): Time-based rotation per language ──
            # VPN_ROTATION_INTERVAL=50 is now checked before EVERY language.
            # Previously only checked at batch start → the 50 s window expired
            # between languages (e.g. after a slow en pass) but rotation was
            # never triggered, leaving a degraded VPN tunnel for remaining langs.
            vpn_rotated: bool = False
            if getattr(cfg, "VPN_ENABLED", False) and self._vpn.should_rotate():
                _elapsed = time.monotonic() - self._vpn._last_rotation
                logger.info(
                    "BUG-VPN-001-FIX: VPN_ROTATION_INTERVAL elapsed "
                    "(%.0fs >= %ds) before %s/%s — rotating",
                    _elapsed,
                    getattr(cfg, "VPN_ROTATION_INTERVAL", 50),
                    url_id,
                    lang,
                )
                try:
                    if self._vpn.rotate(force=False):
                        consecutive_failures = 0
                        ip_known_blocked = False
                        vpn_rotated = True
                        logger.info(
                            "BUG-VPN-001-FIX: time-based rotation OK — "
                            "consecutive_failures reset, ip_known_blocked cleared"
                        )
                    else:
                        logger.warning(
                            "BUG-VPN-001-FIX: time-based rotation returned False "
                            "for %s/%s — proceeding with current IP",
                            url_id,
                            lang,
                        )
                except Exception as _tbe:
                    logger.error(
                        "BUG-VPN-001-FIX: time-based rotation exception "
                        "for %s/%s: %s",
                        url_id,
                        lang,
                        _tbe,
                    )

            # ── VPN rotation decision — failure-triggered (BUG-LANG-001 + 002) ─
            # Skip if time-based rotation above already ran (vpn_rotated=True).
            should_rotate_now: bool = (
                not vpn_rotated
                and getattr(cfg, "VPN_ENABLED", False)
                and (ip_known_blocked or consecutive_failures >= max_consec)
            )

            if should_rotate_now:
                reason = (
                    "ip_known_blocked=True"
                    if ip_known_blocked
                    else f"{consecutive_failures} consecutive failures"
                )
                logger.warning(
                    "BUG-LANG-001-FIX: %s for URL %s — "
                    "forcing VPN rotation before %s",
                    reason, url_id, lang,
                )
                try:
                    rotated: bool = self._vpn.rotate(force=True)
                    if rotated:
                        logger.info(
                            "BUG-LANG-001-FIX: VPN rotated (forced) — "
                            "consecutive_failures reset. Continuing with %s/%s",
                            url_id, lang,
                        )
                        consecutive_failures = 0
                        ip_known_blocked = False
                        vpn_rotated = True
                    else:
                        logger.warning(
                            "BUG-LANG-001-FIX: VPN rotation returned False "
                            "for %s/%s", url_id, lang,
                        )
                except Exception as exc:
                    logger.error(
                        "Forced VPN rotation exception for %s/%s: %s",
                        url_id, lang, exc,
                    )

            # ── BUG-LANG-002-FIX: Browser restart after VPN rotation ──────────
            if vpn_rotated and getattr(cfg, "SELENIUM_RESTART_AFTER_VPN_ROTATE", True):
                reset_ok: bool = self._selenium_engine.reset_browser()
                log_fn = logger.info if reset_ok else logger.warning
                log_fn(
                    "BUG-LANG-002-FIX: Selenium browser reset %s after VPN "
                    "rotation for %s/%s",
                    "OK" if reset_ok else "FAILED",
                    url_id, lang,
                )

            # ── Scrape ────────────────────────────────────────────────────────
            ok: bool = self._scrape_language(url_obj, lang)

            if ok:
                completed.append(lang)
                consecutive_failures = 0
                ip_known_blocked = False
                logger.info("URL %s lang=%s: SUCCESS", url_id, lang)
            else:
                failed.append(lang)
                consecutive_failures += 1
                ip_known_blocked = True
                logger.warning("URL %s lang=%s: FAILED", url_id, lang)

        # ── Finalize URL ──────────────────────────────────────────────────────
        total = len(languages)
        success_count = len(completed)

        if success_count == total:
            logger.info(
                "URL %s: COMPLETE (%d/%d) langs=%s",
                url_id, success_count, total, completed,
            )
        elif success_count > 0:
            logger.warning(
                "URL %s: PARTIAL (%d/%d) completed=%s failed=%s",
                url_id, success_count, total, completed, failed,
            )
        else:
            logger.error("URL %s: ALL FAILED (%d/%d)", url_id, success_count, total)

        final_status = "done" if success_count == total else "error"
        self._finalize_url(url_obj, final_status, completed, failed)

    # ── Per-language scraping ─────────────────────────────────────────────────

    def _scrape_language(self, url_obj: URLQueue, lang: str) -> bool:
        """
        Scrape a single language for the given URL.
        Build 63: Selenium only — CloudScraper removed.
        """
        cfg = self._cfg
        url_id: str = str(url_obj.id)
        lang_url: str = build_language_url(
            url_obj.base_url or str(url_obj.url), lang
        )
        start_ts: float = time.monotonic()

        html: Optional[str] = self._selenium_engine.scrape(lang_url, lang)

        # BUG-VPN-001-FIX (Build 68): Rotate on ANY fetch failure (error-triggered).
        # Previously guarded by should_rotate() — only rotated if VPN_ROTATION_INTERVAL
        # had elapsed, so a failure < 50 s after the last rotation was silently skipped.
        # Now: every fetch failure immediately triggers rotate(force=True), regardless
        # of elapsed time.  force=True bypasses the interval check in NordVPNManager.
        if html is None and getattr(cfg, "VPN_ENABLED", False):
            logger.warning(
                "BUG-VPN-001-FIX: fetch failed for %s/%s — "
                "error-triggered VPN rotation (force=True)",
                url_id,
                lang,
            )
            try:
                rotated: bool = self._vpn.rotate(force=True)
                if rotated:
                        logger.info(
                            "BUG-VPN-001-FIX: VPN rotated (error-triggered) — "
                            "retrying %s/%s with Selenium.",
                            url_id, lang,
                        )
                        if getattr(cfg, "SELENIUM_RESTART_AFTER_VPN_ROTATE", True):
                            self._selenium_engine.reset_browser()
                        html = self._selenium_engine.scrape(lang_url, lang)
                else:
                    logger.error(
                        "BUG-VPN-001-FIX: error-triggered rotation returned False "
                        "for %s/%s — proceeding without new IP",
                        url_id, lang,
                    )
            except Exception as exc:
                logger.error(
                    "BUG-VPN-001-FIX: error-triggered rotation exception "
                    "for %s/%s: %s",
                    url_id, lang, exc,
                )

        duration_ms: int = int((time.monotonic() - start_ts) * 1_000)

        if html is None:
            self._upsert_lang_status(url_obj, lang, "error", "All scraping engines failed")
            self._log_scraping_event(
                url_obj, lang, "scrape_failed", "error",
                duration_ms, "All scraping engines failed",
            )
            return False

        try:
            # BUG-EXTRACTOR-001 (Build 63-fix):
            #   HotelExtractor is a per-page object: html + url + language are
            #   supplied at construction time and the page is parsed immediately.
            #   Correct API: BookingExtractor(html, url, lang).extract_all()
            #   Old call used self._extractor.extract(html, lang) — non-existent
            #   method on a pre-constructed singleton without html (two bugs).
            extractor = BookingExtractor(
                html=html,
                url=lang_url,
                language=lang,
            )
            extracted = extractor.extract_all()
        except Exception as exc:
            logger.error("Extraction failed for %s/%s: %s", url_id, lang, exc, exc_info=True)
            self._upsert_lang_status(url_obj, lang, "error", f"Extraction error: {exc}")
            return False

        if not extracted:
            logger.warning("Extractor returned empty result for %s/%s", url_id, lang)
            self._upsert_lang_status(url_obj, lang, "error", "Extractor returned empty result")
            return False

        try:
            hotel_id = self._persist_hotel_data(url_obj, lang, extracted, duration_ms)
        except Exception as exc:
            logger.error("Persistence failed for %s/%s: %s", url_id, lang, exc, exc_info=True)
            self._upsert_lang_status(url_obj, lang, "error", f"DB write error: {exc}")
            return False

        # Image download — English pass only (photos are language-independent)
        # BUG-PHOTO-001 (Build 63-fix):
        #   extract_all() dropped the "photos" key in v50 ("ELIMINADO").
        #   scraper_service was reading extracted.get("photos", []) → always [].
        #   Fix: call BookingExtractor.extract_hotel_photos() directly on the
        #   scraped html when lang == "en" (photos are language-independent).
        if hotel_id and lang == "en" and html:
            try:
                _photo_extractor = BookingExtractor(
                    html=html,
                    url=lang_url,
                    language="en",
                )
                photos = _photo_extractor.extract_hotel_photos()
                if photos:
                    self._image_downloader.download_photo_batch(
                        hotel_id, photos
                    )
                    # download_photo_batch logs its own summary internally
                else:
                    logger.debug(
                        "No photos extracted for hotel %s (no hotelPhotos JS in page)", hotel_id
                    )
            except Exception as exc:
                logger.warning("Image download failed for hotel %s: %s", hotel_id, exc)

        self._upsert_lang_status(url_obj, lang, "done", None)
        self._log_scraping_event(url_obj, lang, "scrape_success", "done", duration_ms, None)
        return True

    # ── Persistence helpers ───────────────────────────────────────────────────

    def _persist_hotel_data(
        self,
        url_obj: URLQueue,
        lang: str,
        data: dict,
        duration_ms: int,
    ) -> Optional[str]:
        """Upsert hotel data into all relevant tables. Returns hotel UUID."""
        with get_db() as session:
            hotel = self._upsert_hotel(session, url_obj, lang, data, duration_ms)
            hotel_id = str(hotel.id)
            self._upsert_hotel_description(session, url_obj, hotel, lang, data)
            self._upsert_hotel_policies(session, url_obj, hotel, lang, data)
            self._upsert_hotel_legal(session, url_obj, hotel, lang, data)
            # BUG-PERSIST-001 (Build 63-fix): 7 tablas adicionales nunca se persistían
            # porque faltaban las llamadas a sus métodos upsert en este bloque.
            # Los datos sí eran extraídos por HotelExtractor.extract_all() pero
            # eran descartados silenciosamente al no tener destino de escritura.
            self._upsert_hotel_popular_services(session, url_obj, hotel, lang, data)
            self._upsert_hotel_fine_print(session, url_obj, hotel, lang, data)
            self._upsert_hotel_all_services(session, url_obj, hotel, lang, data)
            self._upsert_hotel_faqs(session, url_obj, hotel, lang, data)
            self._upsert_hotel_guest_reviews(session, url_obj, hotel, lang, data)
            self._upsert_hotel_property_highlights(session, url_obj, hotel, lang, data)
            # BUG-PERSIST-002 (Build 77): _upsert_hotel_nearby_places,
            # _upsert_hotel_room_types y _upsert_hotel_seo estaban definidos pero
            # NUNCA se invocaban en este bloque — mismo patrón que BUG-PERSIST-001
            # (Build 63).  Los datos eran extraídos por HotelExtractor.extract_all()
            # pero descartados silenciosamente al no tener destino de escritura,
            # dejando hotels_nearby_places, hotels_room_types y hotels_seo siempre
            # vacíos aunque la extracción funcionase correctamente.
            self._upsert_hotel_nearby_places(session, url_obj, hotel, lang, data)
            self._upsert_hotel_room_types(session, url_obj, hotel, lang, data)
            self._upsert_hotel_seo(session, url_obj, hotel, lang, data)
            # BUG-PERSIST-003 (Build 78): _upsert_hotel_extra_info() was defined
            # but NEVER called here — same silent-discard pattern as BUG-PERSIST-001
            # and BUG-PERSIST-002. hotels_extra_info was always empty despite
            # _extract_extra_info() correctly extracting the data.
            self._upsert_hotel_extra_info(session, url_obj, hotel, lang, data)
            # GAP-SCHEMA-001-FIX (Build 81): _upsert_hotel_individual_reviews()
            # previously missing — same silent-discard pattern as BUG-PERSIST-001/002/003.
            # hotels_individual_reviews was always empty despite table and ORM existing.
            self._upsert_hotel_individual_reviews(session, url_obj, hotel, lang, data)
            # BUG-DOUBLE-COMMIT-001-FIX (Build 84): session.commit() eliminado aquí.
            # get_db() context manager ya llama a session.commit() al salir del bloque
            # 'with'. El commit explícito era redundante: doble commit por cada ciclo
            # de persistencia. La segunda llamada operaba sobre una transacción vacía
            # (sin efecto funcional) pero añadía latencia y riesgo ante futuros cambios
            # en el patrón de uso de la sesión.
            return hotel_id

    def _upsert_hotel(
        self,
        session: Session,
        url_obj: URLQueue,
        lang: str,
        data: dict,
        duration_ms: int,
    ) -> Hotel:
        """Insert or update the main Hotel row for this URL+language."""
        existing = (
            session.query(Hotel)
            .filter_by(url_id=url_obj.id, language=lang)
            .first()
        )
        now = _now()

        fields = {
            "url_id":            url_obj.id,
            "url":               build_language_url(str(url_obj.base_url or url_obj.url), lang),
            "language":          lang,
            "hotel_name":        data.get("hotel_name"),
            "hotel_id_booking":  data.get("hotel_id_booking"),
            "address_city":      data.get("address_city"),
            "latitude":          data.get("latitude"),
            "longitude":         data.get("longitude"),
            "star_rating":       data.get("star_rating"),
            "review_score":      data.get("review_score"),
            "review_count":      data.get("review_count"),
            "main_image_url":    data.get("main_image_url"),
            "short_description": data.get("short_description"),
            "rating_value":      data.get("rating_value"),
            "best_rating":       data.get("best_rating"),
            "street_address":    data.get("street_address"),
            "address_locality":  data.get("address_locality"),
            "address_country":   data.get("address_country"),
            "postal_code":       data.get("postal_code"),
            "room_types":        data.get("room_types"),
            # STRUCT-019/020 (v76): precio disponibilidad y cantidad tipos habitación
            "price_range":       data.get("price_range"),
            "rooms_quantity":    data.get("rooms_quantity"),
            # GAP-EXTRACT-001-FIX (v76 patch) / BUG-SCHEMA-002-FIX (v77):
            # accommodation_type existia en ORM pero faltaba en schema y en upsert.
            "accommodation_type": data.get("accommodation_type"),
            "raw_data":          data.get("raw_data"),
            "scrape_duration_s": duration_ms / 1_000,
            "scrape_engine":     "selenium",   # Build 63: always selenium
            "updated_at":        now,
        }

        if existing:
            for k, v in fields.items():
                setattr(existing, k, v)
            return existing

        hotel = Hotel(**fields, created_at=now)
        session.add(hotel)
        session.flush()
        return hotel

    def _upsert_hotel_description(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelDescription row."""
        from app.models import HotelDescription
        desc_text = data.get("description")
        existing = (
            session.query(HotelDescription)
            .filter_by(url_id=url_obj.id, language=lang)
            .first()
        )
        now = _now()
        if existing:
            existing.description = desc_text
            existing.updated_at = now
        else:
            session.add(
                HotelDescription(
                    hotel_id=hotel.id,
                    url_id=url_obj.id,
                    language=lang,
                    description=desc_text,
                    created_at=now,
                )
            )

    def _upsert_hotel_policies(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelPolicies rows."""
        from app.models import HotelPolicies
        policies: list[dict] = data.get("policies", [])
        for policy in policies:
            policy_name = policy.get("policy_name") or policy.get("name")
            if not policy_name:
                continue
            existing = (
                session.query(HotelPolicies)
                .filter_by(hotel_id=hotel.id, language=lang, policy_name=policy_name)
                .first()
            )
            now = _now()
            if existing:
                existing.policy_details = policy.get("policy_details") or policy.get("details")
            else:
                session.add(
                    HotelPolicies(
                        hotel_id=hotel.id,
                        url_id=url_obj.id,
                        language=lang,
                        policy_name=policy_name,
                        policy_details=policy.get("policy_details") or policy.get("details"),
                        created_at=now,
                    )
                )

    def _upsert_hotel_legal(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """
        Upsert HotelLegal row.

        BUG-DB-002-FIX (v60): Always insert 1 row per hotel/language.
        has_legal_content=True if legal block was found, False if absent.
        """
        from app.models import HotelLegal
        legal_data = data.get("legal") or {}
        has_content = bool(legal_data)

        existing = (
            session.query(HotelLegal)
            .filter_by(hotel_id=hotel.id, language=lang)
            .first()
        )
        now = _now()
        if existing:
            existing.legal             = legal_data.get("legal")
            existing.legal_info        = legal_data.get("legal_info")
            existing.legal_details     = legal_data.get("legal_details")
            existing.has_legal_content = has_content
        else:
            session.add(
                HotelLegal(
                    hotel_id=hotel.id,
                    url_id=url_obj.id,
                    language=lang,
                    legal=legal_data.get("legal"),
                    legal_info=legal_data.get("legal_info"),
                    legal_details=legal_data.get("legal_details"),
                    has_legal_content=has_content,
                    created_at=now,
                )
            )

    def _upsert_hotel_popular_services(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelPopularService rows. BUG-PERSIST-001 (Build 63-fix).
        popular_services = List[str] — una fila por servicio.
        """
        from app.models import HotelPopularService
        services: list = data.get("popular_services") or []
        now = _now()
        for svc in services:
            if not svc or not isinstance(svc, str):
                continue
            exists = (
                session.query(HotelPopularService)
                .filter_by(hotel_id=hotel.id, language=lang, popular_service=svc)
                .first()
            )
            if not exists:
                session.add(HotelPopularService(
                    hotel_id=hotel.id, url_id=url_obj.id, language=lang,
                    popular_service=svc, created_at=now,
                ))

    def _upsert_hotel_fine_print(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelFinePrint row. BUG-PERSIST-001 (Build 63-fix).
        fine_print = Optional[str] — HTML sanitizado, 1 fila por URL+idioma.
        """
        from app.models import HotelFinePrint
        fp_text = data.get("fine_print")
        now = _now()
        existing = (
            session.query(HotelFinePrint)
            .filter_by(url_id=url_obj.id, language=lang)
            .first()
        )
        if existing:
            existing.fp = fp_text
            existing.updated_at = now
        else:
            session.add(HotelFinePrint(
                hotel_id=hotel.id, url_id=url_obj.id, language=lang,
                fp=fp_text, created_at=now, updated_at=now,
            ))

    def _upsert_hotel_all_services(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelAllService rows. BUG-PERSIST-001 (Build 63-fix).

        BUILD-82-FIX (GAP-API-001):
        all_services cambia de List[str] a List[Dict[str,str]] con claves
        {service, service_category}. Se mantiene compatibilidad hacia atrás:
        si un elemento es str (scrapers antiguos / estrategias sin categoría)
        se acepta igualmente con service_category="".
        """
        from app.models import HotelAllService
        raw_services: list = data.get("all_services") or []
        now = _now()
        for item in raw_services:
            # BUILD-82-FIX: aceptar tanto str (legacy) como dict (nuevo)
            if isinstance(item, str):
                svc = item
                svc_category = ""
            elif isinstance(item, dict):
                svc = item.get("service") or ""
                svc_category = (item.get("service_category") or "")[:128]
            else:
                continue

            if not svc:
                continue

            exists = (
                session.query(HotelAllService)
                .filter_by(hotel_id=hotel.id, language=lang, service=svc)
                .first()
            )
            if not exists:
                session.add(HotelAllService(
                    hotel_id=hotel.id,
                    url_id=url_obj.id,
                    language=lang,
                    service=svc,
                    service_category=svc_category or None,
                    created_at=now,
                ))
            elif exists.service_category is None and svc_category:
                # BUILD-82-FIX: backfill category on existing row if now available
                exists.service_category = svc_category

    def _upsert_hotel_faqs(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelFAQ rows. BUG-PERSIST-001 (Build 63-fix).
        faqs = List[Dict] con claves 'ask' y 'answer'.
        """
        from app.models import HotelFAQ
        faqs: list = data.get("faqs") or []
        now = _now()
        for faq in faqs:
            if not isinstance(faq, dict):
                continue
            ask = faq.get("ask") or faq.get("question") or ""
            if not ask:
                continue
            exists = (
                session.query(HotelFAQ)
                .filter_by(hotel_id=hotel.id, language=lang, ask=ask)
                .first()
            )
            if not exists:
                session.add(HotelFAQ(
                    hotel_id=hotel.id, url_id=url_obj.id, language=lang,
                    ask=ask, answer=faq.get("answer"), created_at=now,
                ))

    def _upsert_hotel_guest_reviews(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelGuestReview rows. BUG-PERSIST-001 (Build 63-fix).
        guest_reviews = List[Dict] con 'reviews_categories' y 'reviews_score'.
        """
        from app.models import HotelGuestReview
        reviews: list = data.get("guest_reviews") or []
        now = _now()
        for review in reviews:
            if not isinstance(review, dict):
                continue
            category = (
                review.get("reviews_categories")
                or review.get("category") or ""
            )
            if not category:
                continue
            exists = (
                session.query(HotelGuestReview)
                .filter_by(hotel_id=hotel.id, language=lang,
                           reviews_categories=category)
                .first()
            )
            if not exists:
                session.add(HotelGuestReview(
                    hotel_id=hotel.id, url_id=url_obj.id, language=lang,
                    reviews_categories=category,
                    reviews_score=review.get("reviews_score") or review.get("score"),
                    created_at=now,
                ))

    def _upsert_hotel_property_highlights(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelPropertyHighlights rows. BUG-PERSIST-001 (Build 63-fix).
        property_highlights = List[Dict] con 'category' y 'detail'.
        """
        from app.models import HotelPropertyHighlights
        highlights: list = data.get("property_highlights") or []
        if not isinstance(highlights, list):
            return
        now = _now()
        for item in highlights:
            if not isinstance(item, dict):
                continue
            category = item.get("category") or item.get("highlight_category") or ""
            detail   = item.get("detail")   or item.get("highlight_detail")   or ""
            if not category or not detail:
                continue
            exists = (
                session.query(HotelPropertyHighlights)
                .filter_by(
                    hotel_id=hotel.id, language=lang,
                    highlight_category=category, highlight_detail=detail,
                )
                .first()
            )
            if not exists:
                session.add(HotelPropertyHighlights(
                    hotel_id=hotel.id, url_id=url_obj.id, language=lang,
                    highlight_category=category, highlight_detail=detail,
                    created_at=now,
                ))


    def _upsert_hotel_extra_info(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelExtraInfo row. STRUCT-021 (v76).
        extra_info = Optional[str] — texto del bloque property-important-info.
        1 fila por URL+idioma.
        """
        from app.models import HotelExtraInfo
        ei_text = data.get("extra_info")
        now = _now()
        existing = (
            session.query(HotelExtraInfo)
            .filter_by(url_id=url_obj.id, language=lang)
            .first()
        )
        if existing:
            existing.extra_info = ei_text
            existing.updated_at = now
        else:
            session.add(HotelExtraInfo(
                hotel_id=hotel.id,
                url_id=url_obj.id,
                language=lang,
                extra_info=ei_text,
                created_at=now,
                updated_at=now,
            ))

    def _upsert_hotel_nearby_places(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelNearbyPlace rows. STRUCT-022 (v76).

        BUILD-82-FIX (GAP-SCHEMA-003):
        Persiste category_code (SMALLINT) además de category (VARCHAR).
        La API destino requiere category como INTEGER.
        Mapa en extractor.py: 1=airport 2=restaurant 3=beach
                              4=transport 5=nature 6=attraction
        """
        from app.models import HotelNearbyPlace
        places: list = data.get("nearby_places") or []
        now = _now()
        for place in places:
            if not isinstance(place, dict):
                continue
            place_name = (place.get("place_name") or "").strip()
            if not place_name:
                continue

            # BUILD-82-FIX: extraer category_code del dict del extractor
            raw_code = place.get("category_code")
            category_code: Optional[int] = None
            if raw_code is not None:
                try:
                    code_val = int(raw_code)
                    if 1 <= code_val <= 99:
                        category_code = code_val
                except (TypeError, ValueError):
                    pass

            exists = (
                session.query(HotelNearbyPlace)
                .filter_by(hotel_id=hotel.id, language=lang, place_name=place_name)
                .first()
            )
            if not exists:
                session.add(HotelNearbyPlace(
                    hotel_id=hotel.id,
                    url_id=url_obj.id,
                    language=lang,
                    place_name=place_name,
                    distance=place.get("distance") or None,
                    category=place.get("category") or None,
                    category_code=category_code,          # BUILD-82-FIX
                    created_at=now,
                ))
            elif exists.category_code is None and category_code is not None:
                # BUILD-82-FIX: backfill code on existing row if now available
                exists.category_code = category_code

    def _upsert_hotel_room_types(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelRoomType rows (normalized). STRUCT-023 (v76).
        GAP-SCHEMA-002-FIX (Build 80): ahora persiste adults, children, images, info
        ademas de name/description/facilities, conformando con _API_.md rooms[].
        room_types = List[Dict] con keys: name, description, facilities,
                                          adults, children, images, info.
        Una fila por tipo de habitacion. Complementa hotels.room_types (JSONB).
        """
        from app.models import HotelRoomType
        rooms: list = data.get("room_types") or []
        if not isinstance(rooms, list):
            return
        now = _now()
        for room in rooms:
            if not isinstance(room, dict):
                continue
            room_name = (room.get("name") or "").strip()
            if not room_name or len(room_name) > 256:
                continue
            exists = (
                session.query(HotelRoomType)
                .filter_by(hotel_id=hotel.id, language=lang, room_name=room_name)
                .first()
            )
            facilities = room.get("facilities")
            if facilities and not isinstance(facilities, list):
                facilities = []
            images = room.get("images")
            if images and not isinstance(images, list):
                images = []
            adults   = room.get("adults")
            children = room.get("children")
            info     = room.get("info") or None
            if exists:
                exists.description = room.get("description") or None
                exists.facilities  = facilities or []
                exists.adults      = adults
                exists.children    = children
                exists.images      = images or []
                exists.info        = info
            else:
                session.add(HotelRoomType(
                    hotel_id=hotel.id,
                    url_id=url_obj.id,
                    language=lang,
                    room_name=room_name,
                    description=room.get("description") or None,
                    facilities=facilities or [],
                    adults=adults,
                    children=children,
                    images=images or [],
                    info=info,
                    created_at=now,
                ))

    def _upsert_hotel_seo(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """Upsert HotelSEO row. STRUCT-024 (v76).
        seo = Optional[Dict] con 'seo_description' y/o 'keywords'.
        1 fila por URL+idioma.
        """
        from app.models import HotelSEO
        seo_data: dict = data.get("seo") or {}
        seo_description = seo_data.get("seo_description") or None
        keywords        = seo_data.get("keywords") or None

        # Skip if both fields are empty — no value in inserting empty row
        if not seo_description and not keywords:
            return

        now = _now()
        existing = (
            session.query(HotelSEO)
            .filter_by(url_id=url_obj.id, language=lang)
            .first()
        )
        if existing:
            existing.seo_description = seo_description
            existing.keywords        = keywords
            existing.updated_at      = now
        else:
            session.add(HotelSEO(
                hotel_id=hotel.id,
                url_id=url_obj.id,
                language=lang,
                seo_description=seo_description,
                keywords=keywords,
                created_at=now,
                updated_at=now,
            ))

    # ── Status / logging helpers ──────────────────────────────────────────────

    def _upsert_hotel_individual_reviews(
        self,
        session: Session,
        url_obj: URLQueue,
        hotel: Hotel,
        lang: str,
        data: dict,
    ) -> None:
        """
        GAP-SCHEMA-001-FIX (Build 81): Persiste reseñas textuales individuales
        en hotels_individual_reviews.

        Estrategia: delete-before-insert por (url_id, language).
        Consistente con _upsert_hotel_popular_services(),
        _upsert_hotel_all_services(), _upsert_hotel_faqs() y
        _upsert_hotel_guest_reviews() — todas usan el mismo patrón
        para listas variable-length sin clave natural única.

        Si 'individual_reviews' no está en data o es lista vacía, no opera
        (no elimina filas existentes, preservando datos de scrapes anteriores).
        Esto evita borrar reseñas válidas en re-scrapes parciales donde
        Booking.com no renderizó las review-cards (paginación JS).
        """
        from app.models import HotelIndividualReview

        reviews: List[dict] = data.get("individual_reviews") or []

        if not reviews:
            logger.debug(
                "IndividualReviews upsert: 0 reviews in data — skipping lang=%s", lang
            )
            return

        now = _now()

        # Delete previous rows for this url+language before re-inserting
        deleted = (
            session.query(HotelIndividualReview)
            .filter_by(url_id=url_obj.id, language=lang)
            .delete(synchronize_session=False)
        )
        if deleted:
            logger.debug(
                "IndividualReviews upsert: deleted %d stale rows lang=%s", deleted, lang
            )

        inserted = 0
        for rev in reviews:
            # Clamp score to 0-10 constraint (chk_hir_score)
            score = rev.get("score")
            if score is not None:
                try:
                    score = float(score)
                    if not (0.0 <= score <= 10.0):
                        logger.debug(
                            "IndividualReviews: score %.2f out of [0,10] — "
                            "clamped to None lang=%s", score, lang,
                        )
                        score = None
                except (TypeError, ValueError):
                    score = None

            session.add(HotelIndividualReview(
                hotel_id=hotel.id,
                url_id=url_obj.id,
                language=lang,
                reviewer_name=(rev.get("reviewer_name") or None),
                score=score,
                title=(rev.get("title") or None),
                positive_comment=(rev.get("positive_comment") or None),
                negative_comment=(rev.get("negative_comment") or None),
                reviewer_country=(rev.get("reviewer_country") or None),
                booking_id=(rev.get("booking_id") or None),
                created_at=now,
            ))
            inserted += 1

        logger.debug(
            "IndividualReviews upsert: inserted %d rows lang=%s", inserted, lang
        )

    def _upsert_lang_status(
        self,
        url_obj: URLQueue,
        lang: str,
        status: str,
        error: Optional[str],
    ) -> None:
        """Update URLLanguageStatus for this URL+language combination."""
        with get_db() as session:
            existing = (
                session.query(URLLanguageStatus)
                .filter_by(url_id=url_obj.id, language=lang)
                .first()
            )
            now = _now()
            if existing:
                existing.status     = status
                existing.last_error = (error[:2000] if error else None)
                existing.attempts   = (existing.attempts or 0) + 1
                existing.updated_at = now
            else:
                session.add(
                    URLLanguageStatus(
                        url_id=url_obj.id,
                        language=lang,
                        status=status,
                        last_error=(error[:2000] if error else None),
                        attempts=1,
                        created_at=now,
                        updated_at=now,
                    )
                )
            # BUG-DOUBLE-COMMIT-002-FIX (Build 86): session.commit() removed here.
            # get_db() context manager already commits on clean exit.
            # Explicit commit was redundant and caused two round-trips per call.

    def _log_scraping_event(
        self,
        url_obj: URLQueue,
        lang: str,
        event_type: str,
        status: str,
        duration_ms: int,
        error_message: Optional[str] = None,
        hotel_id: Optional[str] = None,
    ) -> None:
        """Insert a ScrapingLogs record.
        BUG-LOG-001 (Build 63-fix): hotel_id now populated when available,
        enabling JOIN queries between scraping_logs and hotels.
        """
        try:
            import uuid as _uuid
            with get_db() as session:
                session.add(
                    ScrapingLogs(
                        id=_uuid.uuid4(),
                        url_id=url_obj.id,
                        hotel_id=_uuid.UUID(hotel_id) if hotel_id else None,
                        language=lang,
                        event_type=event_type,
                        status=status,
                        duration_ms=duration_ms,
                        error_message=(error_message[:2000] if error_message else None),
                        scraped_at=_now(),
                    )
                )
                # BUG-DOUBLE-COMMIT-002-FIX (Build 86): commit removed — get_db() handles it.
        except Exception as exc:
            logger.warning("Failed to log scraping event: %s", exc)

    def _finalize_url(
        self,
        url_obj: URLQueue,
        status: str,
        completed: list[str],
        failed: list[str],
    ) -> None:
        """Write final status and language lists to url_queue."""
        with get_db() as session:
            db_obj = session.get(URLQueue, url_obj.id)
            if db_obj:
                db_obj.status              = status
                db_obj.languages_completed = ",".join(completed) if completed else ""
                db_obj.languages_failed    = ",".join(failed)    if failed    else ""
                db_obj.scraped_at          = _now()
                db_obj.updated_at          = _now()
                if failed:
                    db_obj.last_error = (
                        f"Incomplete: {len(completed)}/{len(completed)+len(failed)} "
                        f"languages. OK={completed} FAILED={failed}"
                    )[:2000]
                # BUG-DOUBLE-COMMIT-002-FIX (Build 86): commit removed — get_db() handles it.

    def _mark_url_error(self, url_obj: URLQueue, error: str) -> None:
        """Mark a URL as errored due to a fatal exception."""
        with get_db() as session:
            db_obj = session.get(URLQueue, url_obj.id)
            if db_obj:
                db_obj.status     = "error"
                db_obj.last_error = error[:2000]
                db_obj.updated_at = _now()
                # BUG-DOUBLE-COMMIT-002-FIX (Build 86): commit removed — get_db() handles it.

    def _count_successful_languages(self, session: Session, url_id) -> int:
        """Count distinct languages in the hotels table for this URL."""
        from sqlalchemy import func
        result = (
            session.query(func.count(Hotel.language.distinct()))
            .filter(Hotel.url_id == url_id)
            .scalar()
        )
        return result or 0


# =============================================================================
# UTILITIES
# =============================================================================

def _now():
    """Return current UTC datetime."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc)
